// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneSystem___LOLDESIGN.Data;

#nullable disable

namespace PhoneSystem___LOLDESIGN.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhoneSystem___LOLDESIGN.Models.Relation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<double>("PricePerMin")
                        .HasColumnType("float");

                    b.Property<int>("from")
                        .HasColumnType("int");

                    b.Property<int>("to")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Relation");

                    b.HasData(
                        new
                        {
                            id = 1,
                            PricePerMin = 1.8999999999999999,
                            from = 11,
                            to = 16
                        },
                        new
                        {
                            id = 2,
                            PricePerMin = 2.8999999999999999,
                            from = 16,
                            to = 11
                        },
                        new
                        {
                            id = 3,
                            PricePerMin = 1.7,
                            from = 11,
                            to = 17
                        },
                        new
                        {
                            id = 4,
                            PricePerMin = 2.7000000000000002,
                            from = 17,
                            to = 11
                        },
                        new
                        {
                            id = 5,
                            PricePerMin = 0.90000000000000002,
                            from = 11,
                            to = 18
                        },
                        new
                        {
                            id = 6,
                            PricePerMin = 1.8999999999999999,
                            from = 18,
                            to = 11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
